module.exports = {
  appId: 'com.diagpro.desktop',
  productName: 'DiagPro',
  artifactName: 'DiagPro-Setup-${version}.${ext}',
  directories: { output: 'release', buildResources: 'resources' },
  asar: true,
  compression: 'normal',
  npmRebuild: false,
  files: [
    'main.js', 'preload.js', 'appLifecycle.js', 'rendererTarget.js', 'electronPolicy.js',
    'productionLogger.js', 'supportDiagnostic.js', 'deviceDetector.js', 'package.json', 'googleAuth.js',
    'dist/**/*', 'adb/**/*.js', 'security/**/*.js', 'remediation/**/*.js', 'payments/**/*.js',
    '!node_modules/**',
    '!**/*.test.*', '!**/fixtures/**', '!**/.env*', '!**/*.log', '!**/.git/**',
  ],
  extraResources: [{
    from: 'resources/platform-tools',
    to: 'platform-tools',
    filter: ['adb.exe', 'AdbWinApi.dll', 'AdbWinUsbApi.dll', 'NOTICE.txt', 'source.properties', 'MANIFEST.json'],
  }],
  win: {
    target: [{ target: 'nsis', arch: ['x64'] }],
    icon: 'resources/diagpro.ico',
    requestedExecutionLevel: 'asInvoker',
  },
  nsis: {
    oneClick: false,
    perMachine: false,
    allowToChangeInstallationDirectory: true,
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
    shortcutName: 'DiagPro',
    installerIcon: 'resources/diagpro.ico',
    uninstallerIcon: 'resources/diagpro.ico',
  },
  publish: null,
}
